import sys

def this_fails():
	x = 1/0

def get_up():
	try:
		this_fails()
	except ZeroDivisionError as err:
		print("Custom err", err)
	return 'got back up'
		
print(get_up())
	
